# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7cd2e8a54ec20e3f8d6cda6644482b40985ff103228eb4d97c8f1753273473b26f6a051b21ed30d1dda6345c48facbc08e7f0c59b487f9518422f251cc8889

test:
  secret_key_base: 3623d88670547f887236104dd2839dc679bc9702bc14fca4707f31eeffbfe29690b718579159dc0778e40b6564bc013cdf5da53476c8fcb2e4e395efb4de9f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
